name: MusicPlayer
main: org.primesoft.musicplayer.MusicPlayerMain
version: 0.0.1
website: 
dev-url: 
description: 
authors: [SBPrime]
commands:
  mpreload:
    description: 'Reload the config'
    usage: /<command>
    permission: music.player.admin.reload
  test:
    description: ''
    usage: /<command>    
permissions:
  musicplayer.*:
    description: Grants access to all MusicPlayer permissions
    default: op
    children:      
      musicplayer.admin.*: true
  musicplayer.admin.*:
    description: Grants access to all MusicPlayer admin permissions
    default: op
    children:      
      musicplayer.admin.reload: true
  musicplayer.admin.reload:
    description: Allows you to reload MusicPlayer config
    default: op