midiPlayer:
  #Do not change
  version: 1
  #check for updates
  checkVersion: true
  #File containing instrument mapping
  map: default.map
  #File containing drum machine mapping
  drum: default.drm